config/routes.rb
RandomTodo::Application.routes.draw do |map|
  devise_for :users

  resources :tasks do
    member do
      put :delay
      put :i_have_done  
      put :restore
    end
    collection do
      get :finished
      get :next
      get :next_delayed 
      get :delayed 
    end
  end
  
  match 'set_free_time' => 'home#set_free_time'
  root :to => 'home#dashboard'

end

app/models/task.rb
class Task < ActiveRecord::Base
  
  WAITING = 1
  IN_PROGRESS = 2
  DELAYED = 4
  DONE = 8
  
  attr_accessible :essence, :duration, :daypart, :urgency, :status
  
  belongs_to :user
  
  scope :delayed, lambda { where(:status => Task::DELAYED) }
  scope :in_progress, lambda { where(:status => Task::IN_PROGRESS).limit(1) }
  #scope :not_in_progress, lambda { where(:in_progress => false) }
  scope :has_done, where(:status => Task::DONE).order('updated_at DESC')
  scope :is_waiting, lambda { where(:status => Task::WAITING) }
  scope :urgent, lambda { where(:urgency => true) }
  scope :for_current_daypart, lambda { where(:daypart => current_daypart) }
  scope :for_any_daypart, lambda { where(:daypart => 0) }
  scope :in_time, lambda { |free_time| where(['duration <= ?', free_time]) }
  
  def Task.durations(for_select = false)
    d = {15 => 'less than 15 minutes', 60 => 'less than 1 hour', 180 => 'less than 3 hours', 360 => 'more than 3 hours'}
    for_select ? d.invert.to_a.sort : d
  end
  
  def Task.dayparts(for_select = false)
    d = { 0 => 'anytime', 1 => 'night (00:00 - 06:00)', 2 => 'morning (06:00 - 12:00)', 3 => 'day (12:00 - 18:00)', 4 => 'evening  (18:00 - 24:00)'}
    for_select ? d.invert.to_a.sort : d
  end
  
  def Task.urgencies(for_select = false)
    u = { 0 => '', 1 => 'Certainly today'}
    for_select ? u.invert.to_a : u
  end
  
  def Task.current_daypart(t = Time.now)
    case t.to_i - Time.local(t.year, t.month, t.day).to_i
      when 0..21599 then 1
      when 21600..43199 then 2
      when 43200..64799 then 3
      when 64800..86399 then 4
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :confirmable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    if user_signed_in?
      @current_task = Task.in_progress.first
      @tasks_finished = Task.has_done.limit(7)
      @finished_count = Task.has_done.count
      @delayed_count = Task.delayed.count
    else
      render :text => '', :layout => true
    end
  end
  
  def set_free_time
    session[:free_time] = params[:time]
    render :partial => 'shared/flash', :locals => {:name => :notice, :msg => 'Amount of task time is remembered'}
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :check_free_time, :only => [ :next, :next_delayed ]
  before_filter :authenticate_user! 
  def index
    #@tasks = Task.where('status = ? OR status = ?', Task::WAITING, Task::DELAYED).order('updated_at DESC') 
    @tasks = current_user.tasks.is_waiting.order('updated_at DESC') 
  end
  
  def finished
    @tasks = current_user.tasks.has_done
  end
  
  def delayed
    @tasks = current_user.tasks.delayed.order('updated_at DESC')
    render :index
  end
  
  def next
    @task = current_user.tasks.urgent.for_current_daypart.is_waiting.in_time(@free_time).rand
    unless @task
      @task = current_user.tasks.urgent.is_waiting.in_time(@free_time).rand
      unless @task
        @task = current_user.tasks.for_current_daypart.is_waiting.in_time(@free_time).rand
        unless @task
          @task = current_user.tasks.for_any_daypart.is_waiting.in_time(@free_time).rand
        end
      end
    end
    if @task
      Task.update_all({:status => Task::DELAYED}, {:user_id => current_user.id, :status => Task::IN_PROGRESS})
      @task.update_attribute(:status, Task::IN_PROGRESS)
    else
      flash[:notice] = 'No tasks affordable to your amount of time'
    end
    respond_to do |format|
      format.html { redirect_to :root }
      format.js { render :task, :locals => { :update => :next_task }}
    end    
  end
  
  def next_delayed
    @task = current_user.tasks.urgent.for_current_daypart.delayed.in_time(@free_time).rand
    unless @task
      @task = current_user.tasks.urgent.delayed.in_time(@free_time).rand
      unless @task
        @task = current_user.tasks.for_current_daypart.delayed.in_time(@free_time).rand
        unless @task
          @task = current_user.tasks.for_any_daypart.delayed.in_time(@free_time).rand
        end
      end
    end
    if @task
      Task.update_all({:status => Task::DELAYED}, {:user_id => current_user.id, :status => Task::IN_PROGRESS})
      @task.update_attribute(:status, Task::IN_PROGRESS)
    else
      flash[:notice] = 'No tasks affordable to your amount of time'
    end
    respond_to do |format|
      format.html { redirect_to :root }
      format.js { render :task, :locals => { :update => :in_progress }}
    end    
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.build(params[:task])
    if @task.save
      flash[:notice] = "Successfully created task."
      redirect_to tasks_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      flash[:notice] = "Successfully updated task."
      redirect_to tasks_url
    else
      render :action => 'edit'
    end
  end
  
  def i_have_done
    @task = Task.find(params[:id])
    if @task.update_attribute(:status, Task::DONE)
      flash[:notice] = "Successfully updated task."
    else
      flash[:error] = "Something goes wrong."
    end
    redirect_to root_path
  end
  
  def delay
    @task = Task.find(params[:id])
    if @task.update_attribute(:status, Task::DELAYED)
      flash[:notice] = "Successfully updated task."
    else
      flash[:error] = "Something goes wrong."
    end
    redirect_to root_path
  end

  def restore
    @task = Task.find(params[:id])
    if @task.update_attribute(:status, Task::WAITING)
      flash[:notice] = "Successfully updated task."
    else
      flash[:error] = "Something goes wrong."
    end
    @finished_count = current_user.tasks.has_done.count
    respond_to do |format|
      format.html { redirect_to finished_tasks_path }
      format.js
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Successfully destroyed task."
    redirect_to tasks_url
  end
  
  private
    def check_free_time
      @free_time = (session[:free_time] ||= 15).to_i
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @_content_for[:title] = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_color.html.haml
%div
  - %w(fcff68 dbd925 ff8d2c db4f30 962323).each do |color|
    %span{:style => "background-color:##{color};"}= "##{color}"

app/views/home/dashboard.html.haml
%div
  Task time
  = form_tag set_free_time_path, :remote => true, :class => 'time_form' do
    = select_tag :time, options_for_select(Task.durations.invert.sort, session[:free_time].to_i)
    = submit_tag "Save"
- if @current_task
  %h2 Current task is
  %div.next_task
    = render @current_task
- else
  %h2.current
    = link_to 'Current task is', next_tasks_path
  -#%div.next_task


%h3.not_finished
  = link_to "Delayed (#{@delayed_count})", next_delayed_tasks_path
-#%div.in_progress

- unless @tasks_finished.empty?
  %h3.finished
    = link_to "Recently finished tasks (#{@finished_count})", '', { :class => 'recent_toggle' }
  %div.recent_tasks{:style => 'display:none;'}
    %ul
      - for task in @tasks_finished
        %li(id="task_#{task.id}")
          = h(task.essence)
          = link_to 'Restore', restore_task_path(task), :method => :put, :remote => true

    %p= link_to 'See all finished tasks', finished_tasks_path

:javascript
  $(function(){
    $('a.recent_toggle').click(function(){
      $('.recent_tasks').toggle();
      return false;
    })
  });

app/views/layouts/_navigation.html.haml
%div.navigation
  %ul
    %li= link_to 'Dashboard', root_path
    %li= link_to 'Tasks', tasks_path
    %li= link_to 'Delayed', delayed_tasks_path
    %li= link_to 'Create task', new_task_path

app/views/layouts/application.html.haml
!!! Strict
%html{html_attrs}
  
  %head
    %title
      = h(yield(:title) || "Untitled")
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = csrf_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js' 
    = javascript_include_tag 'rails'

    = yield(:head)
  
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      #user_bar.clearfix
        - if user_signed_in?
          = "You are #{current_user.name},"
          = link_to 'Sign out', destroy_user_session_path
        - else
          = link_to 'Sign in', new_user_session_path
          or
          = link_to 'Sign up', new_user_registration_path
      #header.clearfix
        %div.logo Random ToDo List
        = render :partial => 'layouts/navigation'
        -#= render :partial => 'home/color'

      
      - if show_title?
        %h1= yield(:title)
      
      = yield

app/views/shared/_flash.js.erb
$('#container').prepend('<div id="flash_<%= name %>"><%= msg %></div>');
$('#flash_<%= name %>').fadeOut(4000);

app/views/tasks/_form.html.haml
- form_for @task do |f|
  = f.error_messages
  %p
    = f.label :essence
    %br
    = f.text_field :essence
  %p
    = f.label :duration
    %br
    = f.select :duration, Task.durations(true)
  %p
    = f.label :daypart
    %br
    = f.select :daypart, Task.dayparts(true)
  %p
    = f.check_box :urgency
    = f.label :urgency, 'Certainly today?'
  %p
    = f.submit "Save"

app/views/tasks/_task.html.haml
- if task
  %div(class="task status_#{task.status}" id="task_#{task.id}")
    = Task.urgencies[(task.urgency ? 1 : 0 )]
    %span= task.essence
    %br/
    = "it will take #{Task.durations[task.duration]}"
    %br/
    = "and the best time for that is #{Task.dayparts[task.daypart]}"
    - if %w(index show delayed).include?(action_name)
      %br/
      = (task.status == Task::IN_PROGRESS ? 'Already in process' : '' )
      - unless action_name == 'delayed' 
        = (task.status == Task::DELAYED ? 'Delayed' : '' )
      .manage_links
        = link_to 'Edit', edit_task_path(task)
        = link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete
    - elsif %w(finished).include?(action_name)
      .manage_links
        = link_to 'Restore', restore_task_path(task), :method => :put
    - elsif %w(dashboard next_delayed next).include?(action_name)
      .manage_links
        = link_to 'Done', i_have_done_task_path(task), :confirm => 'Are you really done with that?', :method => :put
        - unless action_name == 'next_delayed'
          = link_to 'Delay', delay_task_path(task), :method => :put
- else
  %p No tasks affordable to your amount of time

app/views/tasks/edit.html.haml
- title "Edit Task"

= render 'form'

%p
  = link_to "View All", tasks_path

app/views/tasks/finished.html.haml
- title "Finished tasks"

%div.tasks
  = render @tasks

app/views/tasks/index.html.haml
- title "Tasks"

%div.tasks
  = render @tasks

app/views/tasks/new.html.haml
- title "New Task"

= render 'form'

app/views/tasks/restore.js.erb
<%= render 'shared/flash', :name => :notice, :msg => "Task \"#{@task.essence}\" is restored"%>
$('#task_<%= @task.id %>').remove();
$('.recent_toggle').replaceWith('<%= link_to "Recently finished tasks (#{@finished_count})", '', { :class => 'recent_toggle' } %>')
<% if @finished_count <= 0 %>
$('.finished').remove();
$('.recent_tasks').remove();
<% end %>

app/views/tasks/show.html.haml
- title "Task No. #{@task.id}"

= render @task

%p
  = link_to "View All", tasks_path

app/views/tasks/task.js.erb
<% if @task %>
$('div.<%= update %>').html("<%= escape_javascript(render(@task)) %>");
<% else %>
<%= render 'shared/flash', :name => :notice, :msg => 'No tasks affordable to your amount of time'%>
<% end %>